In [22]:
import requests
import pandas as pd
import numpy as np
import io
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from IPython.display import HTML, clear_output, display

import pandas as pd
from difflib import SequenceMatcher

import io
import ast
import math
import json
import inspect
import pandas as pd
import numpy as np
import ipywidgets as widgets
import matplotlib.pyplot as plt
from IPython.display import clear_output, display
from IPython.display import HTML
import requests.packages.urllib3.util.connection as urllib3_conn

In [ ]:

# SUPABASE_URL = "https://kocihpxevlowqbguhstf.supabase.co"
# SUPABASE_KEY = "sb_publishable_1MWEplxpyp0YOGW_TxZiMQ_HbvtHP5Z"

# HEADERS = {
#     "apikey": SUPABASE_KEY,
#     "Authorization": f"Bearer {SUPABASE_KEY}",
#     "Content-Type": "application/json",
#     "Prefer": "return=representation"}

# def functionGetDataFromTable(tableName: str, url: str, key: str, page_size: int = 1000) -> list:
#     endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?select=*"
#     headers = {
#         "apikey": key.strip(),
#         "Authorization": f"Bearer {key.strip()}",
#         "Content-Type": "application/json",
#     }
#     all_data = []
#     start_index = 0
#     try:
#         while True:
#             page_headers = headers.copy()
#             page_headers["Range"] = f"{start_index}-{start_index + page_size - 1}"
#             response = requests.get(endpoint, headers=page_headers)
#             response.raise_for_status()
#             chunk = response.json()
#             if not chunk:
#                 break  # Stop when no more rows are returned
#             all_data.extend(chunk)
#             if len(chunk) < page_size:
#                 break
#             start_index += page_size
#         print(f"✅ Successfully retrieved ALL {len(all_data)} rows from '{tableName}'")
#         return pd.DataFrame(all_data)
#     except requests.exceptions.HTTPError as http_err:
#         print(f"❌ HTTP error occurred: {http_err}\nResponse details: {response.text}")
#     except Exception as err:
#         print(f"❌ An error occurred: {err}")
#     return None

In [ ]:
# df_ygntbpro_supabase = functionGetDataFromTable("ygntbpro",SUPABASE_URL,SUPABASE_KEY)
# df_ygntbpro_supabase

In [23]:
dfs_dict = {}
upload_widget = widgets.FileUpload(accept=".xlsx, .xlsm", multiple=False, description="Upload Excel")

def on_file_upload(change):
    global dfs_dict
    uploaded_file = list(upload_widget.value)[0]
    file_content = uploaded_file["content"]

    target_sheets = ["YgnTBPro"]      # UNCOMMENT TO LOAD SPECIFIC SHEETS

    try:
        excel_file = pd.ExcelFile(io.BytesIO(file_content))
        dfs_dict = {
            sheet: pd.read_excel(excel_file, sheet_name=sheet)

            for sheet in target_sheets                                        # UNCOMMENT TO LOAD SPECIFIC SHEETS
            if sheet in excel_file.sheet_names                                # UNCOMMENT TO LOAD SPECIFIC SHEETS

            # for sheet in excel_file.sheet_names                             # UNCOMMENT TO LOAD ALL SHEETS
        }

        print(f"Successfully loaded {len(dfs_dict)} sheets into the dictionary!")
    except Exception as e:
        print(f"An error occurred while parsing the file: {e}")
upload_widget.observe(on_file_upload, names="value")
display(upload_widget)

FileUpload(value=(), accept='.xlsx, .xlsm', description='Upload Excel')

In [24]:
print("Sheet List", list(dfs_dict.keys()))

Sheet List ['YgnTBPro']

In [25]:
df_excel = dfs_dict.get('YgnTBPro')
df_excel

,Date,Team,StateRegionName,Tsp,WardVillage,WardCode,Approach,Visit_no,Sr_No,ReportingPeriod,...,Date_drug_pickup_6,Date_drug_pickup_7,Date_drug_pickup_8,Date_drug_pickup_9,TPTdiscontinuationdate,TPTTreatmentOutcome,OutcomeDate,Recstatus_PGK Remark,UniqueKey,TypeofTBTreatment
0,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
1,2026-01-06,1,Yangon,MYG,4 WARD,MMR013042701504,PPM,1,19,1st Qtr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Consortium,1,1.0
2,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
3,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
4,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47185,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,146,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47185,NaN
47186,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,147,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47186,NaN
47187,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,148,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47187,NaN
47188,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,149,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47188,NaN
47189,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,150,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47189,NaN

In [26]:
columnlist = [
    'Date', 'Team', 'StateRegionName', 'Tsp', 'WardVillage', 'WardCode', 
    'Approach', 'Visit_no', 'Sr_No', 'ReportingPeriod', 'RegistrarDate', 
    'TownshipTBRegNumber', 'PatientID', 'Name', 'Nationality', 'Age', 
    'Sex', 'Address', 'Ptstsp', 'PhoneNo', 'Origin', 'VOL', 'Referralfor', 
    'VolunteerName', 'Organization', 'Cough', 'Fever', 'Wtloss', 'Nightsweat', 
    'Haemoptysis', 'Chestpain', 'Fatigue', 'Neckglands', 'TBcontact', 
    'MDRTBcontact', 'TBTreatmenthistory', 'Transferin', 'TypeofPatients', 
    'TypeofDisease', 'SpecifyifEPSiteofEPTB', 'Smoking', 'Reasonforexamination', 
    'TypeofPatient', 'PublicHealthCare1', 'TypeofPatient1', 'DM1', 'RBS', 
    'HbA1c', 'HT1', 'Systolic', 'Diastolic', 'DMHT1', 'RTIAVI1', 
    'Generalweakness1', 'Other1', 'HIVStatus', 'CPT', 'ART', 'Cxrr', 
    'CXRresult', 'Cxr_others', 'Sputum_request', 'Micror', 
    'Sputummicroscopyresult', 'Genexpertrequested', 'GeneXpertresult', 
    'XDRResult', 'Bact_status', 'Case', 'Treatmentreferral', 
    'OLDTYPEOFTBTREATMENT', 'TreatmentRegimen', 'Modifiedregimen', 
    'Placeforreferral', 'Ref1', 'CultureDSTresult', 'Microscope_Result_2nd_mnth', 
    'Xpert_Result_2nd_mnth', 'Microscope_Result_3rd_mnth', 'Xpert_Result_3rd_mnth', 
    'Microscope_Result_5th_mnth', 'Xpert_Result_5th_mnth', 'EndofTxMicroscopeResult', 
    'EndofTxXRayResult', 'EndofTxXpertResult', 'TreatmentOutcome1211', 
    'Tx_Outcome_Date', 'DOTvolName111', 'VolunteerGender111', 
    'VolunteerOrganization111', 'ContactInvestigation111', 'DOTSupervision111', 
    'DOTStartedDate111', 'DOTsupervisiontillTreatmentComp111', 'Seeing1', 
    'Hearing1', 'Walking1', 'Cognition1', 'Selfcare1', 'Communication1', 
    'Disability1', 'Remark', 'MonthDiagnosis11', 'Location11', 'EPI11', 
    'TB11', 'Xray2ndReading11', 'XrayRemark11', 'ReportingTsp11', 
    'CXRresult211', 'XrayEQA11', 'ReportingYear11', 'TPTregno', 
    'RegnoofindexTBcase', 'TPTregistrationdate', 'TPTregimen', 'DrugDose', 
    'Drugpickup1', 'Date_drug_pickup2', 'Date_drug_pickup_3', 
    'Date_drug_pickup_4', 'Date_drug_pickup_5', 'Date_drug_pickup_6', 
    'Date_drug_pickup_7', 'Date_drug_pickup_8', 'Date_drug_pickup_9', 
    'TPTdiscontinuationdate', 'TPTTreatmentOutcome', 'OutcomeDate', 
    'Recstatus', 'UniqueKey', 'TypeofTBTreatment','InitialStartedDate'
]
columnlist = list(dict.fromkeys(columnlist))
df_supabase_ygntbpro = pd.DataFrame(columns=columnlist)
# print(df_supabase_ygntbpro.info())

In [ ]:
# mataexcel

In [27]:
def similarity_score(str1: str, str2: str) -> float:
    return SequenceMatcher(None, str1, str2).ratio() * 100

def align_dataframe_columns(df_primary: pd.DataFrame, df_recipient: pd.DataFrame, threshold: float = 80.0):
    df_recipient_aligned = df_recipient.copy()
    
    primary_cols = list(df_primary.columns)
    recipient_cols = list(df_recipient_aligned.columns)
    
    # 1. Evaluate all combinations of primary and recipient columns globally
    all_pairs = []
    for p_col in primary_cols:
        for r_col in recipient_cols:
            score = similarity_score(p_col, r_col)
            all_pairs.append({
                'ColumnNamePrimary': p_col,
                'ColumnNameRecipient': r_col,
                'SimilarityScore': score
            })
    
    # Sort pairs by score descending to prioritize the best global matches first
    all_pairs.sort(key=lambda x: x['SimilarityScore'], reverse=True)
    
    column_mapping = {}
    matched_primary = set()
    matched_recipient = set()
    matching_records = []
    
    for pair in all_pairs:
        p_col = pair['ColumnNamePrimary']
        r_col = pair['ColumnNameRecipient']
        score = pair['SimilarityScore']
        
        if score < threshold:
            break  # Since sorted descending, all subsequent scores are below threshold
            
        if p_col not in matched_primary and r_col not in matched_recipient:
            matched_primary.add(p_col)
            matched_recipient.add(r_col)
            column_mapping[r_col] = p_col  # Map recipient column name to primary column name
            matching_records.append({
                'ColumnNamePrimary': p_col,
                'ColumnNameRecipient': r_col,
                'SimilarityScore': round(score, 2)
            })

    # 2. Build df_matching and sort from lowest to highest score correctly
    df_matching = pd.DataFrame(matching_records, columns=['ColumnNamePrimary', 'ColumnNameRecipient', 'SimilarityScore'])
    if not df_matching.empty:
        df_matching = df_matching.sort_values(by='SimilarityScore', ascending=True).reset_index(drop=True)
    
    # Identify unmatched columns from both primary and recipient dataframes
    unmatched_recipient_cols = [c for c in recipient_cols if c not in matched_recipient]
    missing_primary_cols = [c for c in primary_cols if c not in matched_primary]
    
    # Build df_unmatching dataframe
    df_unmatching = pd.DataFrame({
        'ColumnNamePrimary': pd.Series(missing_primary_cols, dtype='object'),
        'ColumnNameRecipient': pd.Series(unmatched_recipient_cols, dtype='object')
    })
    
    # Dataframe of dropped recipient columns
    df_drop = df_recipient_aligned[unmatched_recipient_cols].copy()
    
    # Rename matched columns
    df_recipient_aligned.rename(columns=column_mapping, inplace=True)
    
    # Remove duplicate column names if any exist after renaming
    df_recipient_aligned = df_recipient_aligned.loc[:, ~df_recipient_aligned.columns.duplicated()].copy()
    
    # Add missing primary columns filled with None
    for m_col in missing_primary_cols:
        df_recipient_aligned[m_col] = None
        
    df_add = df_recipient_aligned[missing_primary_cols].copy()
    
    # Safely reorder columns to match df_primary layout
    df_recipient_aligned = df_recipient_aligned.reindex(columns=primary_cols)
    
    return df_recipient_aligned, df_drop, df_add, df_matching, df_unmatching

In [28]:
df_recipient = df_excel.copy()
# df_recipient

In [29]:
df_primary = df_supabase_ygntbpro.copy()
# df_primary

In [30]:
# THREADSHOLD SCORE START WITH "0" BUT "80" IS MOSTLY ACCURATE
df_aligned, df_drop, df_add, df_matching, df_unmatching = align_dataframe_columns(df_primary,df_recipient, threshold=10.0)

In [31]:
df_unmatching['ColumnNameRecipient'].to_list()

[nan]

In [32]:
df_aligned

,Date,Team,StateRegionName,Tsp,WardVillage,WardCode,Approach,Visit_no,Sr_No,ReportingPeriod,...,Date_drug_pickup_7,Date_drug_pickup_8,Date_drug_pickup_9,TPTdiscontinuationdate,TPTTreatmentOutcome,OutcomeDate,Recstatus,UniqueKey,TypeofTBTreatment,InitialStartedDate
0,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,None
1,2026-01-06,1,Yangon,MYG,4 WARD,MMR013042701504,PPM,1,19,1st Qtr,...,NaN,NaN,NaN,NaN,NaN,NaN,No Consortium,1,1.0,None
2,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,None
3,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,None
4,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47185,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,146,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47185,NaN,None
47186,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,147,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47186,NaN,None
47187,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,148,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47187,NaN,None
47188,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,149,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47188,NaN,None
47189,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,150,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47189,NaN,None

In [33]:
df_matching.sort_values(by="SimilarityScore")

          ColumnNamePrimary     ColumnNameRecipient  SimilarityScore
0                 Recstatus    Recstatus_PGK Remark            62.07
1                      Date                    Date           100.00
2           StateRegionName         StateRegionName           100.00
3                      Team                    Team           100.00
4               WardVillage             WardVillage           100.00
..                      ...                     ...              ...
127  Sputummicroscopyresult  Sputummicroscopyresult           100.00
128     TPTTreatmentOutcome     TPTTreatmentOutcome           100.00
129             OutcomeDate             OutcomeDate           100.00
130               UniqueKey               UniqueKey           100.00
131       TypeofTBTreatment       TypeofTBTreatment           100.00

[132 rows x 3 columns]

In [34]:
print("Primary Excel File",df_primary.shape)
print("Column Realigment Excel File",df_recipient.shape)

Primary Excel File (0, 133)
Column Realigment Excel File (47190, 132)

In [35]:
print("df_aligned",df_aligned.shape)
print("df_drop",df_drop.shape)
print("df_add",df_add.shape)
print("df_matching",df_matching.shape)

df_aligned (47190, 133)
df_drop (47190, 0)
df_add (47190, 1)
df_matching (132, 3)

In [36]:
print(df_add.columns.to_list())

['InitialStartedDate']

In [37]:
print(df_drop.columns.to_list())

[]

In [ ]:
# RenameColumnDict = {
#     'Treatment Outcome (1-Cure, 2-Complete, 3-Treatment failure,4- Died, 5- LTFU, 6- Not evaluated, 7-Moved to 2nd line, 8-Ongoing treatment)': 'TreatmentOutcome1211',
#     'XrayRemark ': 'XrayRemark11',
#     'Treatment Outcome date': 'Tx_Outcome_Date',
#     'XrayRemark    ': 'XrayRemark11',
#     'TPT regimen    ': 'TPTregimen',
#     'Vol_Name ': 'VolunteerName',
#     'PGK Remark': 'Remark',
#     'Vol_Ref': 'VOL',
#     'Placeforreferral   ': 'Placeforreferral',
#     'Wtloss ': 'Wtloss',
#     'Outcome': 'TPTTreatmentOutcome',
#     'MonthDiagnosis': 'MonthDiagnosis11',
#     'Selfcare   ': 'Selfcare1',
#     'Drug\n&\nDose': 'DrugDose',
#     'Type of TB Treatment (DS_TB/\nDR_TB/TPT)': 'TypeofTBTreatment',
#     'Type_FU': 'TypeofPatient',
#     "Patient's Township":'Ptstsp',
#     'Reason_Ref ':'Referralfor',
#     'Treatment Regimen \n(1=IR, 2=RR, 3=CR, 4=2nd line, 5=Modified Regimen)':'TreatmentRegimen',
#     'Type of MR':'Modifiedregimen',
#     'Treatment Registration':'Treatmentreferral',
#     "Type of Patient's" : "TypeofPatients"
# }

# df_recipient.rename(columns=RenameColumnDict, inplace=True)
# df_recipient

In [38]:
df_matching.sort_values(by="SimilarityScore")

          ColumnNamePrimary     ColumnNameRecipient  SimilarityScore
0                 Recstatus    Recstatus_PGK Remark            62.07
1                      Date                    Date           100.00
2           StateRegionName         StateRegionName           100.00
3                      Team                    Team           100.00
4               WardVillage             WardVillage           100.00
..                      ...                     ...              ...
127  Sputummicroscopyresult  Sputummicroscopyresult           100.00
128     TPTTreatmentOutcome     TPTTreatmentOutcome           100.00
129             OutcomeDate             OutcomeDate           100.00
130               UniqueKey               UniqueKey           100.00
131       TypeofTBTreatment       TypeofTBTreatment           100.00

[132 rows x 3 columns]

In [ ]:
# Reset display
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')
pd.reset_option('display.width')

# Modify Display
pd.set_option('display.max_rows', 200)
# pd.set_option('display.max_columns', 1000)
# pd.set_option('display.width', 1000)

In [39]:


def clean_and_assign_dtypes(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Cleans and standardizes DataFrame data types into universal types (str, int, float, date).
    Compatible with Pandas, Excel, and SQL databases like Supabase.
    
    Returns:
        df: Cleaned DataFrame with standard data types.
        df_error: DataFrame containing unique unparseable values labelled by 
                  'ColumnName (target_type)'.
    """
    df = df.copy()
    errors_dict = {}

    # 1. DATE COLUMNS (Target: date / datetime)
    date_cols = [
        'Date', 'RegistrarDate', 'Tx_Outcome_Date', 
        'DOTStartedDate111', 'TPTregistrationdate', 'Drugpickup1', 
        'Date_drug_pickup2', 'Date_drug_pickup_3', 'Date_drug_pickup_4', 
        'Date_drug_pickup_5', 'Date_drug_pickup_6', 'Date_drug_pickup_7', 
        'Date_drug_pickup_8', 'Date_drug_pickup_9', 'TPTdiscontinuationdate', 
        'OutcomeDate','CPT', 'ART','InitialStartedDate'
    ]

    for col in date_cols:
        if col in df.columns:
            parsed = pd.to_datetime(df[col], errors='coerce')
            
            # Identify values that failed date conversion
            invalid_mask = df[col].notna() & parsed.isna()
            invalid_values = df.loc[invalid_mask, col].unique().tolist()
            if invalid_values:
                errors_dict[f"{col} (date)"] = invalid_values
            
            df[col] = parsed

    # 2. STRING COLUMNS (Target: str)
    # Includes all previously categorical fields + standard text columns
    string_cols = [
        # Categorical text fields converted to str
        'StateRegionName', 'Tsp', 'WardVillage', 'WardCode', 'Approach', 
        'Ptstsp', 'Nationality', 'Organization', 
        'Transferin', 'TypeofPatients', 'TypeofDisease', 'HIVStatus', 
        'XDRResult', 'OLDTYPEOFTBTREATMENT', 'Modifiedregimen', 
        'CultureDSTresult', 'Microscope_Result_2nd_mnth', 'Xpert_Result_2nd_mnth', 
        'Microscope_Result_3rd_mnth', 'Xpert_Result_3rd_mnth', 
        'Microscope_Result_5th_mnth', 'Xpert_Result_5th_mnth', 
        'EndofTxMicroscopeResult', 'EndofTxXRayResult', 'EndofTxXpertResult', 
        'TreatmentOutcome1211', 'VolunteerGender111', 'VolunteerOrganization111', 
        'ContactInvestigation111', 'DOTSupervision111', 
        'DOTsupervisiontillTreatmentComp111', 'MonthDiagnosis11', 'Location11', 
        'EPI11', 'TB11', 'XrayRemark11', 'ReportingTsp11', 'XrayEQA11', 
        'TPTregimen', 'TPTTreatmentOutcome',
        # Regular text / ID fields
        'ReportingPeriod', 'TownshipTBRegNumber', 'PatientID', 'Name', 'Address', 
        'PhoneNo', 'VolunteerName', 'SpecifyifEPSiteofEPTB', 'Other1', 'Cxr_others', 
        'Ref1', 'DOTvolName111', 'Remark', 'TPTregno', 'RegnoofindexTBcase', 
        'DrugDose','Disability1','Recstatus'
    ]

    for col in string_cols:
        if col in df.columns:
            # Cast safely to standard python string, retaining empty/NaN entries correctly
            df[col] = df[col].astype("string")

    # 3. INTEGER COLUMNS (Target: int)
    int_cols = [
        'Team', 'Visit_no', 'Sr_No', 'Age', 'Sex', 'Cough', 'Fever', 'Wtloss', 
        'Nightsweat', 'Haemoptysis', 'Chestpain', 'Fatigue', 'Neckglands', 
        'TBcontact', 'MDRTBcontact', 'TBTreatmenthistory', 'Smoking', 
        'VOL', 'PublicHealthCare1', 'ReportingYear11', 'UniqueKey',
        'Referralfor', 'Reasonforexamination', 'TypeofPatient', 'TypeofPatient1', 
        'DM1', 'HT1', 'DMHT1', 'RTIAVI1', 'Generalweakness1', 'Cxrr', 
        'CXRresult', 'Sputum_request', 'Micror', 'Sputummicroscopyresult', 
        'Genexpertrequested', 'GeneXpertresult', 'Bact_status', 'Case', 
        'Treatmentreferral', 'TreatmentRegimen', 'Placeforreferral', 
        'Seeing1', 'Hearing1', 'Walking1', 'Cognition1', 'Selfcare1', 
        'Communication1', 'Xray2ndReading11', 'CXRresult211', 
        'TypeofTBTreatment','Origin'
    ]

    for col in int_cols:
        if col in df.columns:
            parsed = pd.to_numeric(df[col], errors='coerce')
            invalid_mask = df[col].notna() & parsed.isna()
            invalid_values = df.loc[invalid_mask, col].unique().tolist()
            if invalid_values:
                errors_dict[f"{col} (int)"] = invalid_values

            # Uses 'Int64' to support integer values alongside missing/null entries
            df[col] = parsed.astype('Int64')

    # 4. FLOAT COLUMNS (Target: float)
    float_cols = ['RBS', 'HbA1c', 'Systolic', 'Diastolic']

    for col in float_cols:
        if col in df.columns:
            parsed = pd.to_numeric(df[col], errors='coerce')
            invalid_mask = df[col].notna() & parsed.isna()
            invalid_values = df.loc[invalid_mask, col].unique().tolist()
            if invalid_values:
                errors_dict[f"{col} (float)"] = invalid_values

            df[col] = parsed.astype('float64')

    # Build df_error showing invalid unique values per field type
    if errors_dict:
        df_error = pd.DataFrame(dict([(k, pd.Series(v)) for k, v in errors_dict.items()]))
    else:
        df_error = pd.DataFrame()

    return df, df_error

In [40]:
df_clean,df_error = clean_and_assign_dtypes(df_aligned)

In [41]:
df_error

Empty DataFrame
Columns: []
Index: []

In [ ]:
# SUPABASE_URL = "https://kocihpxevlowqbguhstf.supabase.co"
# SUPABASE_KEY = "sb_publishable_1MWEplxpyp0YOGW_TxZiMQ_HbvtHP5Z"
# TABLE = "ygntbpro"
# HEADERS = {
#     "apikey": SUPABASE_KEY,
#     "Authorization": f"Bearer {SUPABASE_KEY}",
#     "Content-Type": "application/json",
#     "Prefer": "return=representation"
# }
# print("Configuration loaded.")

In [ ]:
# DATE_COLUMNS = ["Date","RegistrarDate","CPT","ART","Tx_Outcome_Date","DOTStartedDate111","TPTregistrationdate",
#     "Drugpickup1","Date_drug_pickup2","Date_drug_pickup_3","Date_drug_pickup_4","Date_drug_pickup_5","Date_drug_pickup_6",
#     "Date_drug_pickup_7","Date_drug_pickup_8","Date_drug_pickup_9","TPTdiscontinuationdate","OutcomeDate"]

# def functionGetDataFromTable(tableName: str, url: str, key: str, page_size: int = 1000) -> list:
#     endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?select=*"
#     headers = {
#         "apikey": key.strip(),
#         "Authorization": f"Bearer {key.strip()}",
#         "Content-Type": "application/json",
#     }
#     all_data = []
#     start_index = 0
#     try:
#         while True:
#             page_headers = headers.copy()
#             page_headers["Range"] = f"{start_index}-{start_index + page_size - 1}"
#             response = requests.get(endpoint, headers=page_headers)
#             response.raise_for_status()
#             chunk = response.json()
#             if not chunk:
#                 break  # Stop when no more rows are returned
#             all_data.extend(chunk)
#             if len(chunk) < page_size:
#                 break
#             start_index += page_size
#         print(f"✅ Successfully retrieved ALL {len(all_data)} rows from '{tableName}'")
#         return pd.DataFrame(all_data)
#     except requests.exceptions.HTTPError as http_err:
#         print(f"❌ HTTP error occurred: {http_err}\nResponse details: {response.text}")
#     except Exception as err:
#         print(f"❌ An error occurred: {err}")
#     return None

# def functionUpdateDataFromDataframe(tableName: str,Dataframe: pd.DataFrame,url: str,key: str,date_columns: list = None,primary_key: str = "PatientID",batch_size: int = 1000,) -> int:

#     date_columns = DATE_COLUMNS
#     if date_columns is None:
#         date_columns = []
#     if Dataframe.empty:
#         print("⚠️ Provided DataFrame is empty. No records to update.")
#         return 0
#     df_update = Dataframe.copy()
#     for col in date_columns:
#         if col in df_update.columns:
#             df_update[col] = pd.to_datetime(df_update[col], errors="coerce")
#             df_update[col] = df_update[col].dt.strftime("%Y-%m-%d")  # Ensures plain Python string or NaN
#     for col in df_update.columns:
#         if col not in date_columns:
#             if df_update[col].dtype == "float64":
#                 try:
#                     df_update[col] = df_update[col].astype("Int64")
#                 except Exception:
#                     pass
#     records = df_update.to_dict(orient="records")
#     clean_records = []
#     for record in records:
#         clean_record = {}
#         for k, v in record.items():
#             if pd.isna(v):
#                 clean_record[k] = None
#             elif isinstance(v, (pd.Timestamp, pd.Timedelta)):
#                 clean_record[k] = v.strftime("%Y-%m-%d")
#             elif isinstance(v, float) and v.is_integer():
#                 clean_record[k] = int(v)
#             else:
#                 clean_record[k] = v
#         clean_records.append(clean_record)
#     total_records = len(clean_records)
#     endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?on_conflict={primary_key}"
#     headers = {
#         "apikey": key.strip(),
#         "Authorization": f"Bearer {key.strip()}",
#         "Content-Type": "application/json",
#         "Prefer": "resolution=merge-duplicates,return=minimal",
#     }
#     total_updated = 0
#     num_batches = math.ceil(total_records / batch_size)
#     print(f"📦 Upserting {total_records} records in {num_batches} batch(es)...")
#     for i in range(0, total_records, batch_size):
#         chunk = clean_records[i : i + batch_size]
#         batch_num = (i // batch_size) + 1
#         try:
#             payload = json.dumps(chunk)
#             response = requests.post(endpoint, headers=headers, data=payload)
#             response.raise_for_status()
#             total_updated += len(chunk)
#             print(f"  ✓ Batch {batch_num}/{num_batches} ({len(chunk)} rows) successful.")
#         except requests.exceptions.HTTPError as http_err:
#             print(f"❌ HTTP error on batch {batch_num}: {http_err}\nResponse: {response.text}")
#             return total_updated
#         except Exception as err:
#             print(f"❌ Error on batch {batch_num}: {err}")
#             return total_updated

#     print(f"✅ Successfully upserted {total_updated} / {total_records} record(s) into '{tableName}'")
#     return total_updated

# def functionDeleteRowByPatientID(tableName: str, patient_id_list: list, url: str, key: str) -> dict:
#     if not patient_id_list:
#         print("⚠️ PatientID list is empty. Nothing to delete.")
#         return None
#     formatted_ids = ",".join(map(str, patient_id_list))
#     endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?PatientID=in.({formatted_ids})"
#     headers = {
#         "apikey": key.strip(),
#         "Authorization": f"Bearer {key.strip()}",
#         "Content-Type": "application/json",
#         # 'return=representation' instructs Supabase to return the deleted rows
#         "Prefer": "return=representation",
#     }
#     try:
#         response = requests.delete(endpoint, headers=headers)
#         response.raise_for_status()

#         deleted_data = response.json()
#         print(f"✅ Successfully deleted {len(deleted_data)} row(s) from '{tableName}'")
#         return pd.DataFrame(deleted_data)
#     except requests.exceptions.HTTPError as http_err:
#         print(f"❌ HTTP error occurred: {http_err}\nResponse details: {response.text}")
#     except Exception as err:
#         print(f"❌ An error occurred: {err}")
#     return None

# def check_duplicate_patient_ids(df: pd.DataFrame, id_col: str = "PatientID") -> pd.DataFrame:
#     duplicate_mask = df.duplicated(subset=[id_col], keep=False)
#     duplicates_df = df[duplicate_mask]
#     num_duplicates = df[id_col].duplicated().sum()
#     print(f"🔍 Found {num_duplicates} duplicate PatientID occurrence(s).")
#     return duplicates_df

# def functionUnmatchingID(df1: pd.DataFrame, df2: pd.DataFrame, id_col: str = "PatientID") -> pd.DataFrame:
#   frame = inspect.currentframe().f_back
#   frame_info = inspect.getframeinfo(frame)
#   df1_name, df2_name = "df1", "df2"
#   if frame_info.code_context:
#     call_line = frame_info.code_context[0].strip()
#     try:
#       # Parse the Python expression into an AST node
#       parsed = ast.parse(call_line).body[0]
#       if isinstance(parsed, ast.Expr) and isinstance(parsed.value, ast.Call):
#         args = parsed.value.args
#         if len(args) >= 1 and isinstance(args[0], ast.Name):
#           df1_name = args[0].id
#         if len(args) >= 2 and isinstance(args[1], ast.Name):
#           df2_name = args[1].id
#     except Exception:
#       pass  # Fallback to default names if parsing fails (e.g. multi-line calls)
#   col1_name = f"ID_{df1_name}"
#   col2_name = f"ID_{df2_name}"
#   s1_ids = df1[id_col].dropna().unique()
#   s2_ids = df2[id_col].dropna().unique()
#   s1 = pd.DataFrame({id_col: s1_ids, col1_name: s1_ids})
#   s2 = pd.DataFrame({id_col: s2_ids, col2_name: s2_ids})
#   merged = pd.merge(s1, s2, on=id_col, how="outer").fillna("")
#   merged = merged.rename(columns={id_col: "ID"})
#   unmatched_df = merged[(merged[col1_name] == "") | (merged[col2_name] == "")].reset_index(drop=True)

#   print(f"⚠️ Found {len(unmatched_df)} unmatched ID(s) between '{df1_name}' and"
#         f" '{df2_name}'.")
#   return unmatched_df[["ID", col1_name, col2_name]]

# def normalize_value(val):
#     if pd.isna(val) or val is None or val is np.nan:
#         return None
#     s_val = str(val).strip()
#     if s_val == "" or s_val.lower() in ("nan", "nat", "none", "null"):
#         return None
#     try:
#         f_val = float(s_val)
#         if f_val.is_integer():
#             return str(int(f_val))
#         return str(f_val)
#     except (ValueError, TypeError):
#         pass
#     return s_val

# def compare_data(dfExcel: pd.DataFrame, dfSupabase: pd.DataFrame, id_col: str = "PatientID",date_cols: list = DATE_COLUMNS) -> pd.DataFrame:
#     records = []
#     dfE = dfExcel.copy()
#     dfS = dfSupabase.copy()
#     dfE[id_col] = dfE[id_col].astype(str).str.strip()
#     dfS[id_col] = dfS[id_col].astype(str).str.strip()
#     for col in date_cols:
#         if col in dfE.columns:
#             dfE[col] = pd.to_datetime(dfE[col], errors="coerce").dt.strftime("%Y-%m-%d")
#         if col in dfS.columns:
#             dfS[col] = pd.to_datetime(dfS[col], errors="coerce").dt.strftime("%Y-%m-%d")
#     ids_dfExcel = set(dfE[id_col].dropna().unique())
#     ids_dfSupabase = set(dfS[id_col].dropna().unique())
#     for pid in ids_dfExcel - ids_dfSupabase:
#         records.append([pid, "_Not in Supabase", pid, None])
#     for pid in ids_dfSupabase - ids_dfExcel:
#         records.append([pid, "_Not in Excel", None, pid])
#     cols_dfExcel = set(dfE.columns) - {id_col}
#     cols_dfSupabase = set(dfS.columns) - {id_col}
#     for col in cols_dfExcel - cols_dfSupabase:
#         records.append([col, "Missing Column in dfSupabase", "Exists", "Missing"])
#     for col in cols_dfSupabase - cols_dfExcel:
#         records.append([col, "Missing Column in dfExcel", "Missing", "Exists"])
#     common_cols = list((set(dfE.columns) & set(dfS.columns)) - {id_col})

#     if common_cols:
#         merged = pd.merge(
#             dfE[[id_col] + common_cols],
#             dfS[[id_col] + common_cols],
#             on=id_col,
#             how="inner",
#             suffixes=("_Excel", "_Supabase"),
#         )
#         for col in common_cols:
#             col_e = f"{col}_Excel"
#             col_s = f"{col}_Supabase"
#             for _, row in merged.iterrows():
#                 pid = row[id_col]
#                 norm1 = normalize_value(row[col_e])
#                 norm2 = normalize_value(row[col_s])
#                 if norm1 is None and norm2 is None:
#                     continue
#                 if norm1 != norm2:
#                     records.append([pid, col, row[col_e], row[col_s]])
#     return pd.DataFrame(records, columns=["PatientID", "ColumnName", "Value_Excel", "Value_Supabase"])

In [42]:
SUPABASE_URL = "https://kocihpxevlowqbguhstf.supabase.co"
SUPABASE_KEY = "sb_publishable_1MWEplxpyp0YOGW_TxZiMQ_HbvtHP5Z"
ALT_CLOUDFLARE_IPS = ["104.16.132.229", "104.18.32.7", "172.67.74.135"]

TABLE = "ygntbpro"
DATE_COLUMNS = ["Date","RegistrarDate","CPT","ART","Tx_Outcome_Date","DOTStartedDate111","TPTregistrationdate",
    "Drugpickup1","Date_drug_pickup2","Date_drug_pickup_3","Date_drug_pickup_4","Date_drug_pickup_5","Date_drug_pickup_6",
    "Date_drug_pickup_7","Date_drug_pickup_8","Date_drug_pickup_9","TPTdiscontinuationdate","OutcomeDate"]

def _create_censorship_resistant_session(host_domain: str, alt_ip: str) -> requests.Session:
  orig_create_connection = urllib3_conn.create_connection
  def patched_create_connection(address, *args, **kwargs):
    host, port = address
    if host == host_domain:
      host = alt_ip
    return orig_create_connection((host, port), *args, **kwargs)
  session = requests.Session()
  urllib3_conn.create_connection = patched_create_connection
  return session


def functionGetDataFromTable(tableName: str, url: str, key: str, page_size: int = 1000) -> pd.DataFrame:
  endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?select=*"
  host_domain = url.replace("https://", "").replace("http://", "").split("/")[0]
  headers = {
      "apikey": key.strip(),
      "Authorization": f"Bearer {key.strip()}",
      "Content-Type": "application/json",
  }
  session = None
  for alt_ip in [None] + ALT_CLOUDFLARE_IPS:
    try:
      if alt_ip is None:
        test_session = requests.Session()
      else:
        test_session = _create_censorship_resistant_session(
            host_domain, alt_ip
        )
      check_res = test_session.get(f"{url}/rest/v1/", headers=headers, timeout=5)
      if check_res.status_code < 500:
        session = test_session
        if alt_ip:
          print(f"⚡ Connected via unblocked Cloudflare route: {alt_ip}")
        break
    except requests.exceptions.RequestException:
      continue

  if session is None:
    print("❌ Failed to reach Supabase across all routes. ISP block may require a Cloudflare Worker Relay.")
    return None

  all_data = []
  start_index = 0

  try:
    while True:
      page_headers = headers.copy()
      page_headers["Range"] = f"{start_index}-{start_index + page_size - 1}"
      response = session.get(endpoint, headers=page_headers, timeout=15)
      response.raise_for_status()
      chunk = response.json()
      if not chunk:
        break
      all_data.extend(chunk)
      if len(chunk) < page_size:
        break
      start_index += page_size

    print(f"✅ Successfully retrieved ALL {len(all_data)} rows from '{tableName}'")
    return pd.DataFrame(all_data)

  except Exception as err:
    print(f"❌ An error occurred during data retrieval: {err}")
    return None

def functionUpdateDataFromDataframe(tableName: str,Dataframe: pd.DataFrame,url: str,key: str,date_columns: list = None,primary_key: str = "PatientID",batch_size: int = 1000,) -> int:

    date_columns = DATE_COLUMNS
    if date_columns is None:
        date_columns = []
    if Dataframe.empty:
        print("⚠️ Provided DataFrame is empty. No records to update.")
        return 0
    df_update = Dataframe.copy()
    for col in date_columns:
        if col in df_update.columns:
            df_update[col] = pd.to_datetime(df_update[col], errors="coerce")
            df_update[col] = df_update[col].dt.strftime("%Y-%m-%d")  # Ensures plain Python string or NaN
    for col in df_update.columns:
        if col not in date_columns:
            if df_update[col].dtype == "float64":
                try:
                    df_update[col] = df_update[col].astype("Int64")
                except Exception:
                    pass
    records = df_update.to_dict(orient="records")
    clean_records = []
    for record in records:
        clean_record = {}
        for k, v in record.items():
            if pd.isna(v):
                clean_record[k] = None
            elif isinstance(v, (pd.Timestamp, pd.Timedelta)):
                clean_record[k] = v.strftime("%Y-%m-%d")
            elif isinstance(v, float) and v.is_integer():
                clean_record[k] = int(v)
            else:
                clean_record[k] = v
        clean_records.append(clean_record)
    total_records = len(clean_records)
    endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?on_conflict={primary_key}"
    headers = {
        "apikey": key.strip(),
        "Authorization": f"Bearer {key.strip()}",
        "Content-Type": "application/json",
        "Prefer": "resolution=merge-duplicates,return=minimal",
    }
    total_updated = 0
    num_batches = math.ceil(total_records / batch_size)
    print(f"📦 Upserting {total_records} records in {num_batches} batch(es)...")
    for i in range(0, total_records, batch_size):
        chunk = clean_records[i : i + batch_size]
        batch_num = (i // batch_size) + 1
        try:
            payload = json.dumps(chunk)
            response = requests.post(endpoint, headers=headers, data=payload)
            response.raise_for_status()
            total_updated += len(chunk)
            print(f"  ✓ Batch {batch_num}/{num_batches} ({len(chunk)} rows) successful.")
        except requests.exceptions.HTTPError as http_err:
            print(f"❌ HTTP error on batch {batch_num}: {http_err}\nResponse: {response.text}")
            return total_updated
        except Exception as err:
            print(f"❌ Error on batch {batch_num}: {err}")
            return total_updated

    print(f"✅ Successfully upserted {total_updated} / {total_records} record(s) into '{tableName}'")
    return total_updated

def functionDeleteRowByPatientID(tableName: str, patient_id_list: list, url: str, key: str) -> dict:
    if not patient_id_list:
        print("⚠️ PatientID list is empty. Nothing to delete.")
        return None
    formatted_ids = ",".join(map(str, patient_id_list))
    endpoint = f"{url.rstrip('/')}/rest/v1/{tableName}?PatientID=in.({formatted_ids})"
    headers = {
        "apikey": key.strip(),
        "Authorization": f"Bearer {key.strip()}",
        "Content-Type": "application/json",
        # 'return=representation' instructs Supabase to return the deleted rows
        "Prefer": "return=representation",
    }
    try:
        response = requests.delete(endpoint, headers=headers)
        response.raise_for_status()

        deleted_data = response.json()
        print(f"✅ Successfully deleted {len(deleted_data)} row(s) from '{tableName}'")
        return pd.DataFrame(deleted_data)
    except requests.exceptions.HTTPError as http_err:
        print(f"❌ HTTP error occurred: {http_err}\nResponse details: {response.text}")
    except Exception as err:
        print(f"❌ An error occurred: {err}")
    return None

def check_duplicate_patient_ids(df: pd.DataFrame, id_col: str = "PatientID") -> pd.DataFrame:
    duplicate_mask = df.duplicated(subset=[id_col], keep=False)
    duplicates_df = df[duplicate_mask]
    num_duplicates = df[id_col].duplicated().sum()
    print(f"🔍 Found {num_duplicates} duplicate PatientID occurrence(s).")
    return duplicates_df

def functionUnmatchingID(df1: pd.DataFrame, df2: pd.DataFrame, id_col: str = "PatientID") -> pd.DataFrame:
  frame = inspect.currentframe().f_back
  frame_info = inspect.getframeinfo(frame)
  df1_name, df2_name = "df1", "df2"
  if frame_info.code_context:
    call_line = frame_info.code_context[0].strip()
    try:
      # Parse the Python expression into an AST node
      parsed = ast.parse(call_line).body[0]
      if isinstance(parsed, ast.Expr) and isinstance(parsed.value, ast.Call):
        args = parsed.value.args
        if len(args) >= 1 and isinstance(args[0], ast.Name):
          df1_name = args[0].id
        if len(args) >= 2 and isinstance(args[1], ast.Name):
          df2_name = args[1].id
    except Exception:
      pass  # Fallback to default names if parsing fails (e.g. multi-line calls)
  col1_name = f"ID_{df1_name}"
  col2_name = f"ID_{df2_name}"
  s1_ids = df1[id_col].dropna().unique()
  s2_ids = df2[id_col].dropna().unique()
  s1 = pd.DataFrame({id_col: s1_ids, col1_name: s1_ids})
  s2 = pd.DataFrame({id_col: s2_ids, col2_name: s2_ids})
  merged = pd.merge(s1, s2, on=id_col, how="outer").fillna("")
  merged = merged.rename(columns={id_col: "ID"})
  unmatched_df = merged[(merged[col1_name] == "") | (merged[col2_name] == "")].reset_index(drop=True)

  print(f"⚠️ Found {len(unmatched_df)} unmatched ID(s) between '{df1_name}' and"
        f" '{df2_name}'.")
  return unmatched_df[["ID", col1_name, col2_name]]

def normalize_value(val):
    if pd.isna(val) or val is None or val is np.nan:
        return None
    s_val = str(val).strip()
    if s_val == "" or s_val.lower() in ("nan", "nat", "none", "null"):
        return None
    try:
        f_val = float(s_val)
        if f_val.is_integer():
            return str(int(f_val))
        return str(f_val)
    except (ValueError, TypeError):
        pass
    return s_val

def compare_data(dfExcel: pd.DataFrame, dfSupabase: pd.DataFrame, id_col: str = "PatientID",date_cols: list = DATE_COLUMNS) -> pd.DataFrame:
    records = []
    dfE = dfExcel.copy()
    dfS = dfSupabase.copy()
    dfE[id_col] = dfE[id_col].astype(str).str.strip()
    dfS[id_col] = dfS[id_col].astype(str).str.strip()
    for col in date_cols:
        if col in dfE.columns:
            dfE[col] = pd.to_datetime(dfE[col], errors="coerce").dt.strftime("%Y-%m-%d")
        if col in dfS.columns:
            dfS[col] = pd.to_datetime(dfS[col], errors="coerce").dt.strftime("%Y-%m-%d")
    ids_dfExcel = set(dfE[id_col].dropna().unique())
    ids_dfSupabase = set(dfS[id_col].dropna().unique())
    for pid in ids_dfExcel - ids_dfSupabase:
        records.append([pid, "_Not in Supabase", pid, None])
    for pid in ids_dfSupabase - ids_dfExcel:
        records.append([pid, "_Not in Excel", None, pid])
    cols_dfExcel = set(dfE.columns) - {id_col}
    cols_dfSupabase = set(dfS.columns) - {id_col}
    for col in cols_dfExcel - cols_dfSupabase:
        records.append([col, "Missing Column in dfSupabase", "Exists", "Missing"])
    for col in cols_dfSupabase - cols_dfExcel:
        records.append([col, "Missing Column in dfExcel", "Missing", "Exists"])
    common_cols = list((set(dfE.columns) & set(dfS.columns)) - {id_col})

    if common_cols:
        merged = pd.merge(
            dfE[[id_col] + common_cols],
            dfS[[id_col] + common_cols],
            on=id_col,
            how="inner",
            suffixes=("_Excel", "_Supabase"),
        )
        for col in common_cols:
            col_e = f"{col}_Excel"
            col_s = f"{col}_Supabase"
            for _, row in merged.iterrows():
                pid = row[id_col]
                norm1 = normalize_value(row[col_e])
                norm2 = normalize_value(row[col_s])
                if norm1 is None and norm2 is None:
                    continue
                if norm1 != norm2:
                    records.append([pid, col, row[col_e], row[col_s]])
    return pd.DataFrame(records, columns=["PatientID", "ColumnName", "Value_Excel", "Value_Supabase"])

In [43]:
df_supabase = functionGetDataFromTable(TABLE,SUPABASE_URL,SUPABASE_KEY)
df_supabase

⚡ Connected via unblocked Cloudflare route: 104.18.32.7
✅ Successfully retrieved ALL 41243 rows from 'ygntbpro'

,Date,Team,StateRegionName,Tsp,WardVillage,WardCode,Approach,Visit_no,Sr_No,ReportingPeriod,...,Date_drug_pickup_8,Date_drug_pickup_9,TPTdiscontinuationdate,TPTTreatmentOutcome,OutcomeDate,Recstatus,TypeofTBTreatment,UniqueKey,InitialStartedDate,updated_at
0,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,349,NaN,...,None,None,None,None,None,1,NaN,32011,None,2026-10-01T07:08:56.120231+00:00
1,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,350,NaN,...,None,None,None,None,None,1,NaN,32012,None,2026-10-01T07:08:56.120231+00:00
2,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,351,NaN,...,None,None,None,None,None,1,NaN,32013,None,2026-10-01T07:08:56.120231+00:00
3,2026-01-06,1,Yangon,MYG,4 WARD,MMR013042701504,PPM,1,19,1st Qtr,...,None,None,None,None,None,1,1.0,2,None,2026-10-01T07:08:56.120231+00:00
4,2026-01-05,1,Yangon,MYG,4 WARD,MMR013042701504,PPM,1,16,1st Qtr,...,None,None,None,None,None,1,1.0,14,None,2026-10-01T07:08:56.120231+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41238,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,334,NaN,...,None,None,None,None,None,1,NaN,31996,None,2026-10-01T07:08:56.120231+00:00
41239,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,335,NaN,...,None,None,None,None,None,1,NaN,31997,None,2026-10-01T07:08:56.120231+00:00
41240,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,336,NaN,...,None,None,None,None,None,1,NaN,31998,None,2026-10-01T07:08:56.120231+00:00
41241,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,337,NaN,...,None,None,None,None,None,1,NaN,31999,None,2026-10-01T07:08:56.120231+00:00
41242,2026-04-27,5,NaN,HTY,Industrial Zone(HTY-Dong Long Factory),MMR013047701504,Mobile Visit,13,338,NaN,...,None,None,None,None,None,1,NaN,32000,None,2026-10-01T07:08:56.120231+00:00

In [44]:
df_aligned

,Date,Team,StateRegionName,Tsp,WardVillage,WardCode,Approach,Visit_no,Sr_No,ReportingPeriod,...,Date_drug_pickup_7,Date_drug_pickup_8,Date_drug_pickup_9,TPTdiscontinuationdate,TPTTreatmentOutcome,OutcomeDate,Recstatus,UniqueKey,TypeofTBTreatment,InitialStartedDate
0,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,None
1,2026-01-06,1,Yangon,MYG,4 WARD,MMR013042701504,PPM,1,19,1st Qtr,...,NaN,NaN,NaN,NaN,NaN,NaN,No Consortium,1,1.0,None
2,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,None
3,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,None
4,2026-01-05,1,NaN,MYG,4 WARD,MMR013042701504,PPM,1,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47185,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,146,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47185,NaN,None
47186,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,147,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47186,NaN,None
47187,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,148,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47187,NaN,None
47188,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,149,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47188,NaN,None
47189,2026-09-23,5,NaN,HTY,Industrial Zone(HTY-DIXINDA_Myanmar) Factory,MMR013047701504,Mobile Visit,28,150,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47189,NaN,None

In [45]:
df_excel = df_aligned.copy()

In [46]:
logSheet = compare_data(df_excel,df_supabase)
logSheet['ColumnName'].value_counts()

ColumnName
Recstatus                  41235
UniqueKey                  39853
_Not in Supabase            5955
Tsp                         1284
ReportingTsp11              1284
                           ...
Sr_No                          1
EndofTxMicroscopeResult        1
Reasonforexamination           1
Modifiedregimen                1
Cxrr                           1
Name: count, Length: 68, dtype: int64

In [47]:
logSheet

           PatientID        ColumnName    Value_Excel Value_Supabase
0      1HTY2623M0365  _Not in Supabase  1HTY2623M0365           None
1      1HTY2624M0284  _Not in Supabase  1HTY2624M0284           None
2      5HTY2627M0047  _Not in Supabase  5HTY2627M0047           None
3      5KMD2609P0308  _Not in Supabase  5KMD2609P0308           None
4      5HTY2627M0390  _Not in Supabase  5HTY2627M0390           None
...              ...               ...            ...            ...
94901  1MYG2608P0125   GeneXpertresult            0.0            NaN
94902  1MYG2608P0152   GeneXpertresult            0.0            NaN
94903  1MYG2608P0154   GeneXpertresult            0.0            NaN
94904  1MYG2608P0221   GeneXpertresult            6.0            NaN
94905  5SDG2608P0052   GeneXpertresult            NaN            2.0

[94906 rows x 4 columns]

In [48]:
logSheet['ColumnName'].value_counts().to_dict()

{'Recstatus': 41235,
 'UniqueKey': 39853,
 '_Not in Supabase': 5955,
 'Tsp': 1284,
 'ReportingTsp11': 1284,
 'DOTSupervision111': 831,
 'ContactInvestigation111': 819,
 'VolunteerGender111': 730,
 'TPTregistrationdate': 720,
 'DOTStartedDate111': 684,
 'Drugpickup1': 536,
 'OutcomeDate': 196,
 'ReportingPeriod': 105,
 'StateRegionName': 105,
 'TownshipTBRegNumber': 56,
 'TypeofPatients': 55,
 'TPTregno': 45,
 'Remark': 42,
 'TypeofTBTreatment': 33,
 'RegnoofindexTBcase': 32,
 'Disability1': 31,
 'TypeofDisease': 22,
 'VolunteerOrganization111': 21,
 'DOTvolName111': 20,
 'Tx_Outcome_Date': 19,
 'Organization': 17,
 'Treatmentreferral': 11,
 'Placeforreferral': 11,
 'RegistrarDate': 11,
 'TreatmentOutcome1211': 10,
 'CPT': 10,
 'ART': 9,
 'TreatmentRegimen': 9,
 '_Not in Excel': 8,
 'CXRresult211': 7,
 'Sex': 7,
 'TPTregimen': 7,
 'DrugDose': 7,
 'GeneXpertresult': 7,
 'Bact_status': 5,
 'Date_drug_pickup_3': 4,
 'Transferin': 4,
 'Date_drug_pickup2': 4,
 'HIVStatus': 4,
 'Nationality': 4,
 'Cognition1': 3,
 'Selfcare1': 3,
 'Communication1': 3,
 'Hearing1': 3,
 'Seeing1': 3,
 'Name': 2,
 'Case': 2,
 'CXRresult': 2,
 'Walking1': 2,
 'Missing Column in dfExcel': 1,
 'Sputum_request': 1,
 'Genexpertrequested': 1,
 'Micror': 1,
 'Microscope_Result_5th_mnth': 1,
 'Xray2ndReading11': 1,
 'RBS': 1,
 'TypeofPatient': 1,
 'Microscope_Result_2nd_mnth': 1,
 'Sr_No': 1,
 'EndofTxMicroscopeResult': 1,
 'Reasonforexamination': 1,
 'Modifiedregimen': 1,
 'Cxrr': 1}

In [49]:
functionUnmatchingID(df_supabase,df_excel)

⚠️ Found 5963 unmatched ID(s) between 'df_supabase' and 'df_excel'.

                 ID ID_df_supabase    ID_df_excel
0     1EDG2605P0179  1EDG2605P0179
1     1EDG2605P0180  1EDG2605P0180
2     1EDG2605P0181  1EDG2605P0181
3     1HTY2622M0001                 1HTY2622M0001
4     1HTY2622M0002                 1HTY2622M0002
...             ...            ...            ...
5958  5SDG2609P2284                 5SDG2609P2284
5959  5SDG2609P2285                 5SDG2609P2285
5960  5SDG2609P2286                 5SDG2609P2286
5961  5SDG2609P2287                 5SDG2609P2287
5962  5SDG2609P2288                 5SDG2609P2288

[5963 rows x 3 columns]

In [50]:
missing = logSheet[logSheet['ColumnName'] == "_Not in Excel"]
missing

          PatientID     ColumnName Value_Excel Value_Supabase
5955  1SPT2608P0393  _Not in Excel        None  1SPT2608P0393
5956  1EDG2605P0179  _Not in Excel        None  1EDG2605P0179
5957  1EDG2605P0181  _Not in Excel        None  1EDG2605P0181
5958  1SPT2606P0468  _Not in Excel        None  1SPT2606P0468
5959  1EDG2605P0180  _Not in Excel        None  1EDG2605P0180
5960  1TGG2604D0202  _Not in Excel        None  1TGG2604D0202
5961  1SPT2606P0469  _Not in Excel        None  1SPT2606P0469
5962  1SPT2606P0467  _Not in Excel        None  1SPT2606P0467

In [51]:
MissingPatientID_Excel = logSheet[logSheet['ColumnName'] == "_Not in Excel"]
listMissingPatientID_Excel = MissingPatientID_Excel['PatientID'].to_list()
print(listMissingPatientID_Excel)

['1SPT2608P0393', '1EDG2605P0179', '1EDG2605P0181', '1SPT2606P0468', '1EDG2605P0180', '1TGG2604D0202', '1SPT2606P0469', '1SPT2606P0467']

In [52]:
functionDeleteRowByPatientID(TABLE,listMissingPatientID_Excel,SUPABASE_URL,SUPABASE_KEY)

✅ Successfully deleted 0 row(s) from 'ygntbpro'

Empty DataFrame
Columns: []
Index: []

In [53]:
df_supabase_check_duplicate = check_duplicate_patient_ids(df_supabase)
print(df_supabase_check_duplicate["PatientID"].to_list())
df_supabase_check_duplicate

🔍 Found 0 duplicate PatientID occurrence(s).
[]

Empty DataFrame
Columns: [Date, Team, StateRegionName, Tsp, WardVillage, WardCode, Approach, Visit_no, Sr_No, ReportingPeriod, RegistrarDate, TownshipTBRegNumber, PatientID, Name, Nationality, Age, Sex, Address, Ptstsp, PhoneNo, Origin, VOL, Referralfor, VolunteerName, Organization, Cough, Fever, Wtloss, Nightsweat, Haemoptysis, Chestpain, Fatigue, Neckglands, TBcontact, MDRTBcontact, TBTreatmenthistory, Transferin, TypeofPatients, TypeofDisease, SpecifyifEPSiteofEPTB, Smoking, Reasonforexamination, TypeofPatient, PublicHealthCare1, TypeofPatient1, DM1, RBS, HbA1c, HT1, Systolic, Diastolic, DMHT1, RTIAVI1, Generalweakness1, Other1, HIVStatus, CPT, ART, Cxrr, CXRresult, Cxr_others, Sputum_request, Micror, Sputummicroscopyresult, Genexpertrequested, GeneXpertresult, XDRResult, Bact_status, Case, Treatmentreferral, OLDTYPEOFTBTREATMENT, TreatmentRegimen, Modifiedregimen, Placeforreferral, Ref1, CultureDSTresult, Microscope_Result_2nd_mnth, Xpert_Result_2nd_mnth, Microscope_Result_3rd_mnth, Xpert_Result_3rd_mnth, Microscope_Result_5th_mnth, Xpert_Result_5th_mnth, EndofTxMicroscopeResult, EndofTxXRayResult, EndofTxXpertResult, TreatmentOutcome1211, Tx_Outcome_Date, DOTvolName111, VolunteerGender111, VolunteerOrganization111, ContactInvestigation111, DOTSupervision111, DOTStartedDate111, DOTsupervisiontillTreatmentComp111, Seeing1, Hearing1, Walking1, Cognition1, Selfcare1, Communication1, ...]
Index: []

[0 rows x 134 columns]

In [54]:
df_excel_check_duplicate = check_duplicate_patient_ids(df_excel)
print(df_excel_check_duplicate["PatientID"].to_list())
df_excel_check_duplicate

🔍 Found 0 duplicate PatientID occurrence(s).
[]

Empty DataFrame
Columns: [Date, Team, StateRegionName, Tsp, WardVillage, WardCode, Approach, Visit_no, Sr_No, ReportingPeriod, RegistrarDate, TownshipTBRegNumber, PatientID, Name, Nationality, Age, Sex, Address, Ptstsp, PhoneNo, Origin, VOL, Referralfor, VolunteerName, Organization, Cough, Fever, Wtloss, Nightsweat, Haemoptysis, Chestpain, Fatigue, Neckglands, TBcontact, MDRTBcontact, TBTreatmenthistory, Transferin, TypeofPatients, TypeofDisease, SpecifyifEPSiteofEPTB, Smoking, Reasonforexamination, TypeofPatient, PublicHealthCare1, TypeofPatient1, DM1, RBS, HbA1c, HT1, Systolic, Diastolic, DMHT1, RTIAVI1, Generalweakness1, Other1, HIVStatus, CPT, ART, Cxrr, CXRresult, Cxr_others, Sputum_request, Micror, Sputummicroscopyresult, Genexpertrequested, GeneXpertresult, XDRResult, Bact_status, Case, Treatmentreferral, OLDTYPEOFTBTREATMENT, TreatmentRegimen, Modifiedregimen, Placeforreferral, Ref1, CultureDSTresult, Microscope_Result_2nd_mnth, Xpert_Result_2nd_mnth, Microscope_Result_3rd_mnth, Xpert_Result_3rd_mnth, Microscope_Result_5th_mnth, Xpert_Result_5th_mnth, EndofTxMicroscopeResult, EndofTxXRayResult, EndofTxXpertResult, TreatmentOutcome1211, Tx_Outcome_Date, DOTvolName111, VolunteerGender111, VolunteerOrganization111, ContactInvestigation111, DOTSupervision111, DOTStartedDate111, DOTsupervisiontillTreatmentComp111, Seeing1, Hearing1, Walking1, Cognition1, Selfcare1, Communication1, ...]
Index: []

[0 rows x 133 columns]

In [56]:
functionUpdateDataFromDataframe(TABLE,df_excel,SUPABASE_URL,SUPABASE_KEY)

📦 Upserting 47190 records in 48 batch(es)...
❌ HTTP error on batch 1: 400 Client Error: Bad Request for url: https://kocihpxevlowqbguhstf.supabase.co/rest/v1/ygntbpro?on_conflict=PatientID
Response: {"code":"22P02","details":null,"hint":null,"message":"invalid input syntax for type numeric: \"No Consortium\""}

0